### ISSUE TITLE
README.md: Span records are only emitted after the span is complete or N minutes have passed.

### ISSUE THREAD

**Issue by miccagiann** [xoplog/xop-go#10]
Since spans can be updated, why not emit the span directly at the moment of creating it and at the moment of completing just update it? I believe is more complicated to enforce an N minutes policy and it prone to resulting to non-existing parent spans...

**Comment by muir** [comment]
Updates are tricky.  At BlueOwl, where we had something similar, we were careful to trap `panic()` and always `Flush()` the current log.  That worked.

Of course, other logs might be lost with a panic, but the one that caused the panic was retained.

This behavior is up to the particular base loggers.  There is no requirement that base loggers buffer or only emit spans at Flush().

**Comment by miccagiann** [comment]
Okay, now that I am thinking it more, it might not be something that the library itself can control. It is up to the user to write code in such a way that those scenarios can be handled... Do you envision users using the "N minutes policy"?
